service: reap-web

provider:
  name: aws
  deploymentMethod: direct
  runtime: python3.9
  stage: dev
  region: eu-central-1
  memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  packRequirements: false
  pythonBin: python3

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http:
          method: any
          path: /{proxy+}